REPORT ZJPP_FORMATION7.

INCLUDE ZJPP_FORMATION7_TOP.
INCLUDE ZJPP_FORMATION7_SCR.
INCLUDE ZJPP_FORMATION7_F01.



START-OF-SELECTION.


*  PERFORM SELECT_DATA_COMMANDE.
PERFORM SELECT_DATA_COMMANDEF.


  END-OF-SELECTION.